In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

import seaborn as sns

sns.set()

In [2]:
wine=pd.read_excel('http://taanila.fi/wine.xlsx')
wine.head(50)

Y     X1    X2    X3    X4   X5    X6    X7    X8    X9   X10   X11   X12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   
5   1  14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97  6.75  1.05  2.85   
6   1  14.39  1.87  2.45  14.6   96  2.50  2.52  0.30  1.98  5.25  1.02  3.58   
7   1  14.06  2.15  2.61  17.6  121  2.60  2.51  0.31  1.25  5.05  1.06  3.58   
8   1  14.83  1.64  2.17  14.0   97  2.80  2.98  0.29  1.98  5.20  1.08  2.85   
9   1  13.86  1.35  2.27  16.0   98  2.98  3.15  0.22  1.85  7.22  1.01  3.55   
10  1  14.10  2.16  2.30  18.0  105  2.95  3.32  0.22  2.38  5.75  1.25  3.17   
11  1  14.12  1.48  2.32  16.8   95  2.20  2.43  0.26  1.57  5.00  1.17  2.82   
12  1  13.75  1.73  2.41  16.0   89  2.60  2.76  0.29  1.81  5.60  1.15  2.90   
13  1  14.75  1.73  2.39  11.4   91  3.10  3.69  0.43  2.81  5.40  1.25  2.73   
14  1  14.38  1.87  2.38  12.0  102  3.30  3.64  0.29  2.96  7.50  1.20  3.00   
15  1  13.63  1.81  2.70  17.2  112  2.85  2.91  0.30  1.46  7.30  1.28  2.88   
16  1  14.30  1.92  2.72  20.0  120  2.80  3.14  0.33  1.97  6.20  1.07  2.65   
17  1  13.83  1.57  2.62  20.0  115  2.95  3.40  0.40  1.72  6.60  1.13  2.57   
18  1  14.19  1.59  2.48  16.5  108  3.30  3.93  0.32  1.86  8.70  1.23  2.82   
19  1  13.64  3.10  2.56  15.2  116  2.70  3.03  0.17  1.66  5.10  0.96  3.36   
20  1  14.06  1.63  2.28  16.0  126  3.00  3.17  0.24  2.10  5.65  1.09  3.71   
21  1  12.93  3.80  2.65  18.6  102  2.41  2.41  0.25  1.98  4.50  1.03  3.52   
22  1  13.71  1.86  2.36  16.6  101  2.61  2.88  0.27  1.69  3.80  1.11  4.00   
23  1  12.85  1.60  2.52  17.8   95  2.48  2.37  0.26  1.46  3.93  1.09  3.63   
24  1  13.50  1.81  2.61  20.0   96  2.53  2.61  0.28  1.66  3.52  1.12  3.82   
25  1  13.05  2.05  3.22  25.0  124  2.63  2.68  0.47  1.92  3.58  1.13  3.20   
26  1  13.39  1.77  2.62  16.1   93  2.85  2.94  0.34  1.45  4.80  0.92  3.22   
27  1  13.30  1.72  2.14  17.0   94  2.40  2.19  0.27  1.35  3.95  1.02  2.77   
28  1  13.87  1.90  2.80  19.4  107  2.95  2.97  0.37  1.76  4.50  1.25  3.40   
29  1  14.02  1.68  2.21  16.0   96  2.65  2.33  0.26  1.98  4.70  1.04  3.59   
30  1  13.73  1.50  2.70  22.5  101  3.00  3.25  0.29  2.38  5.70  1.19  2.71   
31  1  13.58  1.66  2.36  19.1  106  2.86  3.19  0.22  1.95  6.90  1.09  2.88   
32  1  13.68  1.83  2.36  17.2  104  2.42  2.69  0.42  1.97  3.84  1.23  2.87   
33  1  13.76  1.53  2.70  19.5  132  2.95  2.74  0.50  1.35  5.40  1.25  3.00   
34  1  13.51  1.80  2.65  19.0  110  2.35  2.53  0.29  1.54  4.20  1.10  2.87   
35  1  13.48  1.81  2.41  20.5  100  2.70  2.98  0.26  1.86  5.10  1.04  3.47   
36  1  13.28  1.64  2.84  15.5  110  2.60  2.68  0.34  1.36  4.60  1.09  2.78   
37  1  13.05  1.65  2.55  18.0   98  2.45  2.43  0.29  1.44  4.25  1.12  2.51   
38  1  13.07  1.50  2.10  15.5   98  2.40  2.64  0.28  1.37  3.70  1.18  2.69   
39  1  14.22  3.99  2.51  13.2  128  3.00  3.04  0.20  2.08  5.10  0.89  3.53   
40  1  13.56  1.71  2.31  16.2  117  3.15  3.29  0.34  2.34  6.13  0.95  3.38   
41  1  13.41  3.84  2.12  18.8   90  2.45  2.68  0.27  1.48  4.28  0.91  3.00   
42  1  13.88  1.89  2.59  15.0  101  3.25  3.56  0.17  1.70  5.43  0.88  3.56   
43  1  13.24  3.98  2.29  17.5  103  2.64  2.63  0.32  1.66  4.36  0.82  3.00   
44  1  13.05  1.77  2.10  17.0  107  3.00  3.00  0.28  2.03  5.04  0.88  3.35   
45  1  14.21  4.04  2.44  18.9  111  2.85  2.65  0.30  1.25  5.24  0.87  3.33   
46  1  14.38  3.59  2.28  16.0  102  3.25  3.17  0.27  2.19  4.90  1.04  3.44   
47  1  13.90  1.68  2.12  16.0  101  3.10  3.39  0.21  2.14  6.10  0.91  3.33   
48  1  14.10  2.02  2.40  18.8  103

In [3]:
X = wine.drop('Y', axis=1)

y = wine['Y']

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=5)

In [5]:
from sklearn.naive_bayes import GaussianNB

malli = GaussianNB()
malli.fit(X_train, y_train)

y_train_malli = malli.predict(X_train)
y_test_malli = malli.predict(X_test)

In [7]:
from sklearn.metrics import accuracy_score

accuracy_score(y_train, y_train_malli)

0.9924812030075187

In [11]:
accuracy_score(y_test, y_test_malli)

0.9333333333333333

In [13]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_train, y_train_malli))

[[40  0  0]
 [ 0 56  1]
 [ 0  0 36]]
